# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MineralietyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MineralietyApp

  target 'MineralietyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'Stripe', '~> 9.2.0'
